apiVersion: v1
kind: Service
metadata:
  name: apollosai
  namespace: apollosai
  labels:
    app.kubernetes.io/name: apollosai
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: apollosai
    app.kubernetes.io/component: app
