"""initial schema

Revision ID: bd818a71a520
Revises: faeef06e7fea
Create Date: 2026-02-17 01:35:50.552448
"""

from typing import Sequence, Union

revision: str = 'bd818a71a520'
down_revision: Union[str, None] = 'faeef06e7fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
