apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: apollosai
  namespace: apollosai
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: apollosai
      app.kubernetes.io/component: app
